site_name: My Docs

# Deployment Version
extra:
  version: 1.0
  social:
    - icon: fontawesome/brands/buffer
      link: https://jam4.sapjam.com/groups/about_page/GGDxi7Gsb5xr8reaKrQ2EL
      name: SAP JAM
    - icon: fontawesome/solid/info-circle
      link: https://help.sap.com/viewer/p/SAP_TRANSPORTATION_RESOURCE_PLANNING
      name: TRP - SAP Help

nav:
  - About me: about_me.md
  - Github Repos: repos.md
  - Documentations:
      - Git Commands: git_commands.md
      - Markdown Docs: mkdown_docs.md
      - Regex: regex.md
      - Node.js best practices: nodejs.md
      - System Design: system_design.md
      - Unit Testing: unit_testing.md
      - Docker: docker.md

theme:
  name: "material"
  logo: img/ship_blue.png
  font:
    # text: Roboto
    text: "Asap"
    # code: "Roboto Mono"
    code: "Oxygen Mono"
  favicon: img/sap-logo.png
  # features:
  #   - tabs
  icon:
    repo: fontawesome/brands/github
    # More icons at https://fontawesome.com/icons?d=gallery&m=free
  palette:
    scheme: preference
    # scheme: slate
    # scheme: default
    primary: light blue
    accent: deep orange
    # custom_dir: override/
  # include_sidebar: false
  hljs_languages:
    - yaml
  prev_next_buttons_location: top

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - css/extra.css