site_name: My Docs

# Deployment Version
extra:
  version: 1.0
  social:
    - icon: fontawesome/brands/buffer
      link: https://jam4.sapjam.com/groups/about_page/GGDxi7Gsb5xr8reaKrQ2EL
      name: SAP JAM
    - icon: fontawesome/solid/info-circle
      link: https://help.sap.com/viewer/p/SAP_TRANSPORTATION_RESOURCE_PLANNING
      name: TRP - SAP Help

nav:
  - Overview: index.md
  - Details:
      - Details1: detail1.md
      - Details2: detail2.md

theme:
  name: "material"
  logo: img/ship_blue.png
  font:
    # text: Roboto
    text: "Asap"
    # code: "Roboto Mono"
    code: "Oxygen Mono"
  favicon: img/sap-logo.png
  # features:
  #   - tabs
  icon:
    repo: fontawesome/brands/github
    # More icons at https://fontawesome.com/icons?d=gallery&m=free
  palette:
    scheme: preference
    # scheme: slate
    # scheme: default
    primary: light blue
    accent: deep orange
    # custom_dir: override/
  # include_sidebar: false
  hljs_languages:
    - yaml
  prev_next_buttons_location: top